[worker]
allowed_domains = [ "localhost", "172.16.0.1", "worker.osbuild.org" ]
ca = "/etc/osbuild-composer/ca-crt.pem"

[koji]
allowed_domains = [ "localhost", "172.16.0.1", "worker.osbuild.org" ]
ca = "/etc/osbuild-composer/ca-crt.pem"
