#!/bin/bash

sudo podman run \
--rm -d \
-v ./config:/etc/osbuild-composer \
-v ./config:/etc/osbuild-worker \
-e CACHE_DIRECTORY=/var/cache/osbuild-worker \
--privileged \
--cap-add MKNOD \
--cap-add SYS_ADMIN \
--cap-add NET_ADMIN \
--pod osbuild-pod \
--name worker worker
